// components/code/index.tsx
import styles from "./styles.module.scss";

interface Props {
  className: string,
  children?: React.ReactNode;
}

export default function Code(props: Props) {
  const { children, className } = props;
  return (
    <div className={styles.codeblock}>
      <header>
        <button>⬤</button>
      </header>
      <pre className={className}>{children}</pre>
    </div>
  );
}

// src/lib/components/code/code.svelte
<script lang="ts">
  let maximized = false;
  let portal: HTMLElement;
  let code: HTMLElement;

  function toggle() {
    if (!maximized) {
      maximized = true;
      document.body.appendChild(code);
    } else {
      maximized = false;
      portal.appendChild(code);
    }
  }
</script>

<div class="portal" bind:this={portal}>
  <div class="codeblock" bind:this={code} class:maximized>
    <header>
      <button on:click={toggle}>⬤</button>
    </header>
    <slot />
  </div>
</div>

<style lang="scss">
  @use "./styles.scss" as *;
</style>
