// src/lib/components/date.svelte
<script lang="ts">
  import { Chip } from "$lib";

  let stamp: number = +new Date();
  let formatted = "";
  let isNew = false;

  const week = 6.048e8;
  const now = +new Date();

  $: formatted = new Date(stamp).toLocaleString();
  $: isNew = now - stamp < week;

  export { stamp };
</script>

<em>
  {#if isNew}<Chip type="new">new</Chip>{/if}
  Posted: {formatted}
</em>

<style lang="scss">
  @use "$lib/tokens/scss" as *;

  em {
    font-size: 0.9rem;
    display: inline-block;
    color: $color-neutral-300;
    margin-bottom: $spacing-level-200;
  }
</style>

// components/date/index.tsx
import { Chip } from "$components";
import styles from "./styles.module.scss";
import { useState, useEffect } from "react";
const week = 6.048e8;

interface Props {
  stamp: number;
}

export default function PostDate(props: Props) {
  const [formatted, setFormatted] = useState("");
  const [isNew, setIsNew] = useState(false);

  useEffect(() => {
    const now = +new Date();
    setFormatted(new Date(props.stamp).toLocaleString());
    setIsNew(now - props.stamp < week);
  }, [props.stamp]);

  return (
    <em className={styles.date}>
      {isNew && <Chip type="new">new</Chip>}
      Posted: {formatted}
    </em>
  );
}
